farzad/lesson-1/farzad
mehrzadnaini/tutorial pull request #3
Opened 2022-05-21 09:40 UTC by farzadabdollahi

2022-05-22 18:10 UTC, mehrzadnaini requested changes

2022-05-22 18:10 UTC, mehrzadnaini commented on lesson-1/farzad/index.html
> +      <div class="top-left"></div>
Same here `top-left` is a general name which may defined in other toolkits such as bootstrap and you may get some unwanted styles.
One of the best methodologies which you can use is BEM please check following documentation
http://getbem.com/introduction/

2022-05-22 18:10 UTC, mehrzadnaini commented on lesson-1/farzad/index.html
> +  </head>
It's better if you use HTML5 meta tags 
you don't need to remember them you should know the reason why we need them and use vscode `html snippets` 
```suggestion
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logo</title>
        <link rel="stylesheet" href="./styles.css" />
</head>
```

2022-05-22 18:10 UTC, mehrzadnaini commented on lesson-1/farzad/styles.css
> +    width: 10vw;
```suggestion
    width: 10vw;
    height:10vw
```

2022-05-22 18:10 UTC, mehrzadnaini commented on lesson-1/farzad/styles.css
> +    /* border-radius: 100%; */
```suggestion
```

2022-05-22 18:10 UTC, mehrzadnaini commented on lesson-1/farzad/styles.css
> +    margin-top: 200px;
The aim of this task is to create a responsive logo that changes based on the screen width so we should not use `px`

2022-05-23 10:59 UTC, mehrzadnaini requested changes

2022-05-23 10:59 UTC, mehrzadnaini commented on lesson-1/farzad/index.html
> +      <div class="grid4"></div>
```suggestion
      <div class="logo_grid1"></div>
      <div class="logo_grid2"></div>
      <div class="logo_grid3"></div>
      <div class="logo_grid4"></div>
```

2022-05-23 10:59 UTC, mehrzadnaini commented on lesson-1/farzad/styles.css
> +.grid2 {
On `CSS` files it's better to sort your code based on usage 
e.g 
.grid1{
}
.grid2{
}
....

2022-05-23 16:50 UTC, farzadabdollahi commented on lesson-1/farzad/styles.css
> +.grid2 {
Ok i will correct it.thanks

2022-05-27 13:04 UTC, mehrzadnaini approved these changes

2022-05-27 13:05 UTC, merged